# Generated by Django 3.1.7 on 2021-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_data_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='heating_fuel_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='total_number_of_rooms',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
